//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookSeek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ledger
    {
        public int TrackId { get; set; }
        public string Isbn { get; set; }
        public int Quantity { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public string TrackTag { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
