//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookSeek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.Sale_Book = new HashSet<Sale_Book>();
        }
    
        public int SaleId { get; set; }
        public System.DateTime TransactionDateTime { get; set; }
        public string SaleStatus { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal Cash { get; set; }
        public decimal Change { get; set; }
        public Nullable<decimal> ChargePrepaid { get; set; }
        public Nullable<decimal> AdditionalRequired { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale_Book> Sale_Book { get; set; }
    }
}
